### ISSUE TITLE
Kaynak kod için lisans

### ISSUE THREAD

**Issue by maidis** [tayfunulu/DovizKurlari#4]
Benim de buna benzer bir araca ihtiyacım doğdu bugün. Yalnız kodu kullanabilmem için lisansını bilmem gerekiyor. Rica etsem bir lisans belirleyebilir misiniz? Şurası [1] belki yardımcı olabilir. Benim için MIT lisansı [2] harika olurdu ama tercih tabii ki sizin.

[1] http://ozgurlisanslar.org.tr/
[2] https://tr.wikipedia.org/wiki/MIT_Lisans%C4%B1

**Comment by tayfunulu** [comment]
Telefondan yapmaya çalıştım ama sanırım script çalıştığı için seçemiyorum. Lisans dosyası ekledim MIT seçtim. umarım işinizi götür.

**Comment by tayfunulu** [comment]
selamlar, MIT lisansı ile lisanslanmıştır. Nerede nasıl kullandığınızı paylaşırsanız sevinirim :) 

kolay gelsin

**Comment by maidis** [comment]
Lisanslama için teşekkürler. Kodunuzu Celery ile birlikte aşağıdaki projede kullandık, henüz canlıya yansımadı ama yansıdığı zaman sizin kodunuz sayesinde sabit bir kur değeri yerine o günkü kur değerini kullanabileceğiz :)

https://www.evetsigorta.com/
