### ISSUE TITLE
Düzeltme

### ISSUE THREAD

**Issue by erayerturk** [tayfunulu/DovizKurlari#5]
Unit değişkeni eksik. Indexlerin kaymasına neden oluyor.

DovizKurları.py

self.son [Kod] = [Kod,isim,CurrencyName,ForexBuying,ForexSelling,BanknoteBuying,BanknoteSelling,CrossRateUSD]

>>

self.son [Kod] = [Kod,Unit,isim,CurrencyName,ForexBuying,ForexSelling,BanknoteBuying,BanknoteSelling,CrossRateUSD]

**Comment by tayfunulu** [comment]
Selamlar, Haklısın nasıl kaçmış aradan. teşekkürler. düzelttim.

**Comment by tayfunulu** [comment]
bu arada sizinki de yanlış olmuş dökümana göre sıralamayı düzelttim. 

self.son [Kod] = [Kod,isim,CurrencyName,Unit,ForexBuying,ForexSelling,BanknoteBuying,BanknoteSelling,CrossRateUSD]
